name: 'nest-project-test-build'

on:
  push:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run build script
        run: ./build.sh

      - name: Upload Jest report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: reports/jest-junit.xml
