name: 'nest-project-test-build'

on:
  push:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn

      - name: Run build script
        run: ./build.sh

      - name: Upload Jest report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: reports/jest-junit.xml
